### ISSUE TITLE
How to add a static "home" page

### ISSUE THREAD

**Issue by Lesilva** [seanosaur/sydney#2]
Hey man,

Just trying to understand how do you use http://seanosaur.com as a static page and http://blog.seanosaur.com/ goes to the blog.

Thanks

**Comment by seanoldham** [comment]
I have it hacked together with GitHub Pages for seanosaur.com and it just links to the Ghost blog at blog.seanosaur.com. Same theme, two different setups.

Static page can be found here https://github.com/seanosaur/seanosaur.github.io

**Comment by Lesilva** [comment]
Thanks!

**Comment by seanoldham** [comment]
No problem, let me know if you have any other questions or feature ideas.
